services:
  - type: worker
    name: estoque-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    # CRÍTICO: Usa Gunicorn com worker assíncrono (gevent) para suportar a rota 'async def webhook()'.
    # 'main:app_flask' instrui o Gunicorn a carregar a variável 'app_flask' do arquivo 'main.py'.
    startCommand: gunicorn --bind 0.0.0.0:$PORT -w 4 main:app_flask --worker-class gevent
