services:
  - type: web
    name: estoque-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app_flask --worker-class gevent --workers 1
    envVars:
      - key: PORT
        value: 10000
